server:
  port: 8087

spring:
  application:
    name: 06-eureka-client-hystrix-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka9100:9100/eureka,http://eureka9200:9200/eureka

#  开启健康检查机制的所有端口
management:
  endpoints:
    web:
      exposure:
        include: "*"