server:
  port: 8086

spring:
  application:
    name: 06-eureka-client-hystrix-provider
eureka:
  client:
    service-url:
      defaultZone: http://eureka9100:9100/eureka,http://eureka9200:9200/eureka