server:
  port: 9200
eureka:
  instance:
    hostname: eureka9200
  client:
    register-with-eureka: false
#   保证客户端能够去注册中心中拉取服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka9100:9100/eureka
spring:
  application:
    name: eureka9200